### ISSUE TITLE
GT Editor:  Scoping not working for HOT

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#110]
See https://github.com/mde-lab-sessions/running-example-for-lecture/blob/hot-bug/de.upb.mbse.taxcalculationexample.hot/src/de/upb/mbse/taxcalculationexample/hot/Rules.gt

For some reason the scoping does not work for some cases (references to internal metamodels).

**Comment by patrickrobrecht** [comment]
1) You're loading `http://www.eclipse.org/emf/2002/Ecore`, but your meta-model contains references to `platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore` such that the references cannot be resolved - that causes the scoping problems.

Importing `platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore` fixes the problem: https://github.com/mde-lab-sessions/running-example-for-lecture/commit/bd6ef3a9fd9d0ea8d4669db255beb2a1ddd4ec75. Another possibility would be to fix the reference to Ecore in the meta-model.

2) After that scoping works perfect, but the generated code contains errors. PR https://github.com/eMoflon/emoflon-ibex/pull/360 fixes an issue that no import statements were generated for EClassifiers from subpackages in the ecore (as in the TGG meta-model you use).
