### ISSUE TITLE
TGG Editor:  TGG rule vis

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#115]
Although one can now choose a rule for visualisation just by placing the cursor in its scope, the **flattened** version of the rule is not visualised.

**Comment by anthonyanjorin** [comment]
Any progress?  Have you been able to reproduce?  Not sure if this is still relevant...  might already be fixed.

**Comment by mvdheram** [comment]
I think this is already fixed in class "EditorTGGtoFlattenedTGG" and visualised in class "IbexTGGVisualiser"

**Comment by mvdheram** [comment]
I have gone through handbook2 and handbook3. Have seen examples of sokoban pattern refinement and rule refinement and flattened version consists of the complete pattern and rules are visualized with refinement included.
