### ISSUE TITLE
[Victory] Show all rules right from the start

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#142]
I suggest we show all rules in the left "tree", even if there are no children (available matches).

The reason is that when matches appear the order of the entries in the three can change and it gets hard to "see" what just changed.

It would also be nice to perhaps grey out the rule with no matches.  It would still be helpful to be able to visualise them just like all other rules, but some visual cues indicating that there are no matches (greyed out), there are matches (normal), and there are now new matches added in the very last step (perhaps bold).

**Comment by LegionaryCohort** [comment]
Completed by the recent switch to the `TreeViewer` widget.
The rules are now all displayed from the start and marked appropriately depending on the number of matches and where new matches have appeared.
