### ISSUE TITLE
[Victory] Minor visualisation tweaks

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#143]
Name the buttons consistently.  Right now we have "Apply match" and "Full rule Vis".

I suggest we change the first to just:  "Apply"

For the second button, I suggest we toggle between "Show Only Context" and "Show Full Rule"

Another point:  one of the buttons is on top, one at the bottom of the window :(  

I think it would also be nice to have buttons that are just as big as their label (and do not take the entire width of the window).  As usual, nice icons would be nice to have.

**Comment by LegionaryCohort** [comment]
I don't think toggling the text on the button is helpful. I often find this more confusing than helpful in fact. Does the button tell me what happens when I click on it or is it showing me the current toggle-state?
A simple toggle-button as it is now makes more sense in my opinion.

**Comment by anthonyanjorin** [comment]
Hmm...  the text in a button typically describes what will happen when you press the button.  Just take a look at the buttons here in GitHub :)

**Comment by LegionaryCohort** [comment]
Maybe that's just me overthinking things, but why not just stick with toggle-buttons and replace the text with an icon (and add a tooltip for clarification)?
Essentially sticking to the eclipse design philosophy.

**Comment by anthonyanjorin** [comment]
I don’t see what this has to do with Eclipse design philosophy but yes - a toggle (active vs. inactive with a meaningful icon or title and tool tip would work fine too).

I find my other points to be more important (I’m just having some difficulties thinking of an understandable label for the toggle).

**Comment by LegionaryCohort** [comment]
Along with the switch in layout managers, I've repositioned and resized the buttons.
Their names have yet to be changed, but the new version should look a lot more like you'd want it to.

**Comment by anthonyanjorin** [comment]
The latest buttons are fine....  but I would still rename to:

Apply match ==> Apply
Full rule Vis ==> Full Vis

**Comment by LegionaryCohort** [comment]
I've changed the buttons to what you suggested.

Leaving this issue open for now to discuss further similar changes, should they be necessary.
Just want to avoid spamming issues for minor tweaks.

**Comment by LegionaryCohort** [comment]
Considering that nothing of note has been discussed here for quite some time, I will close this issue now.
Should any changes be required in future, we should open a new issue to discuss those.
