### ISSUE TITLE
[Victory] Initial context needed

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-ibex-ui#145]
When the visualizer starts and no rule has been applied yet, an initial message displayed on the right panel(main screen which is currently empty) would make sense. 
For instance- "Start applying matches" or "No rules applied yet"

**Comment by anthonyanjorin** [comment]
Some default message for trivial context would also be nice.  So instead of an empty windows something along the lines of „No context required“

**Comment by LegionaryCohort** [comment]
This feature is part of the recent changes to user visualisation options.
