### ISSUE TITLE
[Victory] Stop button can be added 

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-ibex-ui#147]
Will be nice to have a stop option in UI to turn off Victory. 
Currently even when the UI window is closed the process is not killed/stopped.

**Comment by anthonyanjorin** [comment]
Perhaps also a „restart“ button meaning discard and just start afresh.

**Comment by saman** [comment]
@Ayurshi, You can stop the UI with the stop button of runtime-environment in the console tab.

**Comment by Ayurshi** [comment]
Also would like to add that if the user runs the MODELGEN_App again (probably after making few changes in java code) without closing the previous victory UI/ process, the previous UI monitor should close/ refresh before the new set is loaded. 
Currently a second UI monitor appears without the precious one being closed.[
![Screen Shot 2019-05-16 at 12 03 43 PM](https://user-images.githubusercontent.com/43295444/57845736-df9da980-77d2-11e9-9ff6-96b528e76328.png)
](url)

**Comment by LegionaryCohort** [comment]
Closing the window now terminates the entire program.
I've also added a seperate "Quit" button that currently does the same thing. If desired, this button could later be expanded to, for example,  a "Save & Quit" button, as opposed to simply closing the window which doesn't save anything.
