### ISSUE TITLE
[Victory] Saving and visualization of model's current state

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-ibex-ui#148]
Would be better if the current sate of the model is saved and can be visualized( not in the UI necessarily).

**Comment by anthonyanjorin** [comment]
Absolutely - a save button would be nice so the current models can be saved with a time stamp perhaps.  One might actually wish to continue generating after saving this snapshot.

**Comment by saman** [comment]
We made two branches for this issue ([victory-monitor_issue_148](eMoflon/emoflon-ibex/commits/victory-monitor_issue_148) and [victory_ui_issue_148](eMoflon/emoflon-ibex-ui/tree/victory_ui_issue_148)).
Right now is look like this and is working properly.

<img width="1162" alt="Screen Shot 2019-05-26 at 17 09 40" src="https://user-images.githubusercontent.com/1576246/58383627-5576f180-7fd9-11e9-8d00-9d22454b09d3.png">

@LegionaryCohort please test it, if it's a proper solution, merge it to main branches.

**Comment by saman** [comment]
We added a timestamp to the file name also.

Right now is like this:
```
corr-1558887177821.xmi
protocol-1558887177821.xmi
trg-1558887177821.xmi
src-1558887177821.xmi
```

**Comment by LegionaryCohort** [comment]
Both the _corr_ and _protocol_ xmi files contain references such as this one: `href="src.xmi#/"`
Due to the files being named with a timestamp, those references cannot be resolved, causing eclipse to display an error when you try to open these files.

_src_ and _trg_ can be opened without any problems.

**Comment by anthonyanjorin** [comment]
This can be fixed by changing the URI of the resources to be saved.  I don't know how you're doing it right now, but changing the URI is the right way to do it and should solve the problem.

**Comment by anthonyanjorin** [comment]
Btw:  the buttons are an absolute mess.  See #143   Adding an additional wide button Save Models just makes things worse.  We now have Apply match, Save Models, and Full rule Vis.  Couldn't be more inconsistent regarding capitalisation.  And having wide buttons filling the entire width of the window looks awful.  Standard is to have small buttons wrapped to the length of their label, typically in the right, bottom corner of the window (see the windows right here in GitHub).

**Comment by LegionaryCohort** [comment]
Working as expected now.
The current state can be saved and model generation can be continued afterwards.
