### ISSUE TITLE
[Victory] Scalable and Scrollable Rule Visualization Window for large rules

### ISSUE THREAD

**Issue by shub1989** [eMoflon/emoflon-ibex-ui#149]

**Comment by anthonyanjorin** [comment]
What exactly does this mean?  Scrollable?

**Comment by shub1989** [comment]
the window should scale-up. because for large rules it is not possible to scale it up after some time. and after some limit can't view apply match button either.

**Comment by anthonyanjorin** [comment]
What does „scale up“ mean?

**Comment by anthonyanjorin** [comment]
Please post a screenshot here showing how things go wrong for a large rule -  I’m having problems understanding what you mean.

**Comment by shub1989** [comment]
![image](https://user-images.githubusercontent.com/45486055/57456601-238e2d00-726e-11e9-8597-6720c9c98804.png)

I am trying to view whole rule but after some time can't scale the window and When i scale it to some limit, Apply Match Button can't be viewed. even if i minimize the window. need to close it and run the modelgen again


![image](https://user-images.githubusercontent.com/45486055/57456866-b0d18180-726e-11e9-8168-abbd76a562a8.png)
After minimizing window, Apply Match Button Can't be viewed

**Comment by anthonyanjorin** [comment]
@shub1989  Please add [Victory] to the title of this issue

**Comment by LegionaryCohort** [comment]
The necessary changes have been merged into the stable _victory_ui_ branch
