### ISSUE TITLE
[Victory] Protocol creation

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-ibex-ui#150]
It would be helpful to have protocol: list of rules that were applied to get the current model (possibly sorted in their order of application) in the right screen panel(possibly).
Will be helpful when the no. of rules applied are too high and visualizing a super big model on UI monitor is not a very feasible idea.

Also would be interesting if each of this rule could be selected individually and the model at that point could be visualized.

Added suggestion: a hierarchical model instead of a flat list protocol would be visually more informative.

**Comment by anthonyanjorin** [comment]
The killer feature here would be to allow a multi-selection of different steps in the protocol and to visualise the sum of selected model elements...

**Comment by LegionaryCohort** [comment]
This feature has now been merged into the stable branches for Victory and can be used.
It supports the suggested multi-selection capabilities.
