### ISSUE TITLE
Remove MigLayout dependency

### ISSUE THREAD

**Issue by LegionaryCohort** [eMoflon/emoflon-ibex-ui#156]
Replace the current third party layout manager with SWT layout managers.

In hindsight, MigLayout does not offer any real additional value over the existing SWT layout managers for Victory. I think it makes sense to completely remove this third party dependency.

Sidenote: I keep having issues with the JAR not being loaded and causing issues. Does anybody else have this problem or is this just my eclipse workspace being annoying?

**Comment by 09Ankita** [comment]
@LegionaryCohort Yes, even I am facing this issue of JAR not being loaded, and because of that not able to run the Victory.

**Comment by LegionaryCohort** [comment]
Completed
