### ISSUE TITLE
[Victory] Adding Dependency in Manifest.mf

### ISSUE THREAD

**Issue by Surbhi2111** [eMoflon/emoflon-ibex-ui#157]
I still need to add the dependency in a new project's MANIFEST.MF file for all the folders in the workspace....
@LegionaryCohort  m attaching a screenshot for the same...
![2019-05-28](https://user-images.githubusercontent.com/45486012/58472729-30a08c80-8147-11e9-9421-152ef2080271.png)

**Comment by LegionaryCohort** [comment]
Just to clarify:
For existing projects, the dependency has to be added manually. This has been discussed with Tony.
The dependency is only automatically added when creating a new project through the project creation wizard.

Please confirm that the latter is not working and remark the issue as a bug if that is the case.

**Comment by Surbhi2111** [comment]
@LegionaryCohort  jetzt i made a new project and tried running the debugger without adding the dependency and its running ...
but when i opened manifest.mf for each folder just to check if the dependency is present or not it wasnt there ... 
![2019-05-28 (1)](https://user-images.githubusercontent.com/45486012/58475422-3057bf80-814e-11e9-9f12-8a43eb31752c.png)

so should it be there or not if no then cool if yes then i will remark the issue

**Comment by LegionaryCohort** [comment]
I'm not sure I understand the problem.
Are you saying that the new project was running fine, despite not having the dependency? That would be very weird...

**Comment by Surbhi2111** [comment]
ahhh i checked again ... yes the dependency is already added in the Tgg project thats y the debugger was running ... 
one question: shouldnt dependency be added in all the folders or its fine if its added in the tgg project folder ... ?

**Comment by LegionaryCohort** [comment]
What do you mean by "all the folders"?
The debugger is only for TGG projects, why would other projects need the dependency?

**Comment by Surbhi2111** [comment]
Initially we used to add the dependency in all the folders... even in the emf projects so i got confused
