### ISSUE TITLE
[Victory] Leave tree unfolded when a match is applied

### ISSUE THREAD

**Issue by LegionaryCohort** [eMoflon/emoflon-ibex-ui#159]
Currently when a match is applied, the tree is repopulated with new matches, causing all elements to be collapsed into their default initial (folded) state.

It would be great if the previously unfolded elements could be left unfolded. Especially for larger projects, this would be a great quality of life improvement.

**Comment by anthonyanjorin** [comment]
Is there no standard SWT support for this?  We can't be the first people to have this problem...

**Comment by LegionaryCohort** [comment]
The current `Tree` widget that I'm using does not support this, but there is a `TreeViewer` widget that appears to support this sort of thing.
I haven't yet had the time to look into this more, but I suspect it will also help a lot with resolving other issues like marking newly created elements and the like.

**Comment by LegionaryCohort** [comment]
Completed as part of the switch to the `TreeViewer` widget.
