### ISSUE TITLE
[Victory] Adjust visualisation for scalability 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#161]
I'm trying to use Victory for a medium-sized rule and have a few suggestions:
- add a button to hide all correspondence labels (this sometimes messes up the layout and is not always absolutely important)
- add a button to automatically restrict all labels in the diagram to a certain fixed size... say 10 characters.  Apache StringUtils has a cool method that takes a few letters from the beginning of the word, from the end, and blends out the middle.  This could be used to provide a summary of every label that is forced to fit in 10 (or perhaps a few more) characters.

Perhaps we should add a (dropdown?) menu to contain all these buttons?

**Comment by LegionaryCohort** [comment]
Correspondence links are currently completely unlabeled.
Is there a use case in which it's necessary to have the correspondence links labeled at all?

**Comment by anthonyanjorin** [comment]
Hmm...  I‘m tempted to agree.  But there are cases where the same two elements are (or can be) connected via different corrs.  In such cases it is crucial to be able to distinguish them.

**Comment by LegionaryCohort** [comment]
In that case I'd say we leave the links unlabeled by default, but include an option that adds those labels, should the user require them.

**Comment by JaneJose** [comment]
We added a combo box on the UI to choose the visualization. The option is stored in the UserOptions and the visualization gets adapted accordingly.

![issue161](https://user-images.githubusercontent.com/34136262/60758666-2a40e280-a01a-11e9-8eb1-3f5551cb09ba.PNG)

**Comment by LegionaryCohort** [comment]
The feature has been merged into the stable branch.
