### ISSUE TITLE
[Victory] Change colour of model elements in visualisation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#162]
Currently we are using the default plantuml vis for model elements.  It's yellowish, however, and thus clashes with our background colour for source domain elements.  Let's switch to plain white (background) and black (outline).

**Comment by LegionaryCohort** [comment]
With a white background it looks like this:
![new](https://user-images.githubusercontent.com/6261260/59612688-d1b6ad80-911d-11e9-9efa-70a30d73a06c.png)

Perhaps we should consider a brighter yellow to make the distinction more obvious?

**Comment by anthonyanjorin** [comment]
Hmm...  I can‘t decide what one wants here.  I had a meeting with QA today and the feeling was that one actually would like to distinguish src and trg model elements also based on their background colour.

What do you think of using the same background colours as in the rule?  I don’t think one would mix up rule and model elements....

**Comment by LegionaryCohort** [comment]
Considering that the rule and models are seperated from each other anyways, that makes a lot of sense.

Will be more involved in terms of implementation though. As far as I'm aware, you can't extract the domain from the model objects directly, can you?

**Comment by anthonyanjorin** [comment]
oh should be easy...   just add the method to the victory interface.

The operational strategy has separate resources for each domain and just needs to do:  srcResource.contains(modelElement)

**Comment by LegionaryCohort** [comment]
I've changed the visualisation to be identical to that of the rule elements.
Personally I find it works, although I do see potential for confusing rule and model elements.

The changes have been merged into the stable branches, so you can go ahead and take a look yourself.

**Comment by LegionaryCohort** [comment]
Can this issue be closed or should we tweak the visualisation a little more?

**Comment by anthonyanjorin** [comment]
Let’s use it like this for a while and find out.
