### ISSUE TITLE
[Victory] Wrong visualisation in normal rule vis (not full)

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#164]
In the full rule vis, to-be-translated elements are visualised differently than context or to-be-created elements (which is good).

But if one switches full rule vis off, these to-be-translated nodes in the rule are then visualised just like model elements.  Something is wrong here.

**Comment by Ayurshi** [comment]
if I am not wrong the below screenshot 
![Screen Shot 2019-06-17 at 9 36 16 PM](https://user-images.githubusercontent.com/43295444/59632776-4bb15b80-914b-11e9-8002-c63843c38d18.png)
showcases this problem as aadlPackage:AadlPackage and aadlPublicPackageSection: PublicPackageSection nodes are visualized like model elements (full rule vis off)

**Comment by JaneJose** [comment]
Has been fixed together with the extension of the visualization options

**Comment by LegionaryCohort** [comment]
All changes have been merged into the stable branch.
