### ISSUE TITLE
[Victory] To-be-translated edges have the wrong color

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-ibex-ui#166]
The to-be-translated edges should be visualized differently, probably in grey color.
Shown below in the screenshot where the edge: ownedClassifier currently shown as context(green) can be greyed out as it is present in trg and needs to-be-translated.
![Screen Shot 2019-06-17 at 8 49 52 PM](https://user-images.githubusercontent.com/43295444/59628905-f755ae00-9141-11e9-9a8a-81ffb09e8e59.png)

**Comment by anthonyanjorin** [comment]
The yellow/orange outline for „translated“ nodes is also not really working out.  I would vote for grey so it looks a bit like context (and it is - just still untranslated context).

**Comment by anthonyanjorin** [comment]
BTW.  This is a nice screenshot for https://github.com/eMoflon/emoflon-ibex-ui/issues/158

**Comment by LegionaryCohort** [comment]
I've tried using different shades of grey, but it's practically indistinguishable from elements with a black border or just looks like there's no border at all.

Perhaps a different color would work better?

**Comment by anthonyanjorin** [comment]
Could you post a picture of a black node and edge, green node and edge, and grey node and edge?

Perhaps also a version with brown instead of grey?

How about using grey and additionally a lighter shade for the node background colour?

**Comment by JaneJose** [comment]
Color: Gold
![Gold](https://user-images.githubusercontent.com/34136262/60757401-68cea100-a00a-11e9-865d-385a5a9ad638.PNG)

**Comment by JaneJose** [comment]
Color: Black
![Black](https://user-images.githubusercontent.com/34136262/60757406-813ebb80-a00a-11e9-93aa-e272c0a84974.PNG)

**Comment by JaneJose** [comment]
Color: Green
![Green](https://user-images.githubusercontent.com/34136262/60757408-8d2a7d80-a00a-11e9-86cc-648afff5950d.PNG)

**Comment by JaneJose** [comment]
Color: DarkGrey
![DarkGrey](https://user-images.githubusercontent.com/34136262/60757415-9ae00300-a00a-11e9-9251-c753dc7f56d6.PNG)

**Comment by JaneJose** [comment]
Color:LightSlateGray
![LightSlateGray](https://user-images.githubusercontent.com/34136262/60757420-a7fcf200-a00a-11e9-8fb2-8f768803ab7b.PNG)

**Comment by JaneJose** [comment]
Color: Brown
![SiennaBrown](https://user-images.githubusercontent.com/34136262/60757426-b3501d80-a00a-11e9-9585-c2d5a9a4430c.PNG)

**Comment by JaneJose** [comment]
I think brown and gold are ones that are most distinguishable. What are your opinions?

**Comment by anthonyanjorin** [comment]
Green and black are out of the question.
Dark grey almost looks like black.

I would take light grey to avoid adding yet another colour with semantics.  Our diagrams are already very colourful.  Grey is “almost“ black and that fits the semantics of untranslated context well enough.

**Comment by 09Ankita** [comment]
Yes, we agree. We can go with light grey. @LegionaryCohort what do you suggest? If everyone is in agreement, then we will make it light grey and commit.

**Comment by LegionaryCohort** [comment]
Personally I find both greys to be difficult to distinguish from black, but perhaps that's just me.

As a side-note: PlantUML allows for a simple diagram key that can explain the colors.
So I'm thinking more into the direction of introducing a new color since it's easier to distinguish, and then adding in a key (that the user can hide if he wants to), that explains the colors.

**Comment by anthonyanjorin** [comment]
Let‘s go with light grey and see how it works.  We can revisit this again if we’re unhappy and decide to open a new issue (I find it hard to decide based on a single example and a screenshot, not sure it’s worth the effort of adding a legend).

**Comment by 09Ankita** [comment]
Changed the color to Light gray. @LegionaryCohort if everything seems okay, you can merge it with the stable branch.

**Comment by LegionaryCohort** [comment]
The changes have been merged into the stable branch.

**Comment by LegionaryCohort** [comment]
The color should be changed to a lighter gray.

**Comment by 09Ankita** [comment]
Is this color better? It's much lighter that LightSlateGray we used previously.
![image](https://user-images.githubusercontent.com/44120336/62011393-2109e800-b178-11e9-8af1-101d992ddf1d.png)

**Comment by anthonyanjorin** [comment]
Looks perfect!  I suggest we take the colour and close this issue.

**Comment by LegionaryCohort** [comment]
The changes have been merged into the stable branch.
