### ISSUE TITLE
[Victory] Cryptic time stamp 

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-ibex-ui#169]
Saved models have extremely cryptic stamp. Difficult to figure out which is the latest saved model(not sorted).
Probably java.util.date can be used to produce something in the following format: T2019-MM-DD-HOUR:MIN:SECS.

**Comment by filipgia** [comment]
The timestamp is now a readable format like this:
```
src-20190625-193425.xmi
```
I think we can close the issue.

**Comment by anthonyanjorin** [comment]
Please add underscores for dummies like me :)

**Comment by filipgia** [comment]
Added!

**Comment by LegionaryCohort** [comment]
The changes have been merged into the stable branch.
