### ISSUE TITLE
[Victory] ArrayIndexOutOfBoundsException causing the debugger to crash

### ISSUE THREAD

**Issue by daryazarkalam** [eMoflon/emoflon-ibex-ui#170]
I am unfortunately not able to reproduce the problem but at some point when using the debugger it crashes, showing this exception at the selection (Line 50) shown in the screenshot. It is supposedly because it is assuming that the selection is non-empty.
![Screen Shot 2019-06-17 at 11 40 28 AM](https://user-images.githubusercontent.com/22117295/59635492-a5b51f80-9151-11e9-955f-3646875f8703.png)

**Comment by LegionaryCohort** [comment]
This was likely fixed by the recent switch to the TreeViewer widget, but without steps to reproduce I can't be sure.

**Comment by LegionaryCohort** [comment]
Please monitor whether this issue still persists in the current version of Victory.
