### ISSUE TITLE
[Victory] Load/Save models with drag and drop

### ISSUE THREAD

**Issue by saman** [eMoflon/emoflon-ibex-ui#171]
Regarding #148, @anthonyanjorin suggested it's good if the user can load/save models via drag and drop feature.

**Comment by anthonyanjorin** [comment]
Loading certainly....  for saving I’m not so sure.  A dialogue would probably be best for saving.

**Comment by LegionaryCohort** [comment]
Closing this as it is covered by #165 and #167
