### ISSUE TITLE
[Victory] Protocol View Is not As expected for Whole Model.

### ISSUE THREAD

**Issue by shub1989** [eMoflon/emoflon-ibex-ui#173]
When we select protocols to view complete model, some elements are not having edge from the respected element. But save model saves the model in correctly as expected.
![image](https://user-images.githubusercontent.com/45486055/61009865-75d5f200-a374-11e9-9ce6-cdca2483a495.png)

![img11](https://user-images.githubusercontent.com/45486055/61002652-4ae2a280-a362-11e9-8367-5d9f35336cd5.png)
So in above example for protocol steps to view whole model, for wifi node should have edge from connection type. Emailfrom and attachement should have edge from showeamil and reademail. as the model shown correctly when we click save model in other image.

**Comment by JaneJose** [comment]
The problem was, that only containment edges were shown, but not any cross references. We fixed the problem.

**Comment by LegionaryCohort** [comment]
All changes have been merged into the stable branch.
