### ISSUE TITLE
[Victory] Invalid Protocol view

### ISSUE THREAD

**Issue by Surbhi2111** [eMoflon/emoflon-ibex-ui#174]
when I click on protocol step to visualise the model generated at the moment i am getting the output as in the image below... I am unable to see models when i click on a particular or all protocol steps..  For eg when i clicked on Protocol step#0 
![2019-07-10](https://user-images.githubusercontent.com/45486012/61009062-b97b2c80-a371-11e9-9dae-6875920673d4.png)

Sometimes I even get the similar display when i choose _GEN file..  For eg when i clicked on UserNetworkBridgeRule_GEN
![2019-07-10 (2)](https://user-images.githubusercontent.com/45486012/61009075-c435c180-a371-11e9-9ea5-cdbf4e7dd71f.png)

I checked console to see if there is any error but there were no errors.

**Comment by LegionaryCohort** [comment]
@Surbhi2111 You indicated that you no longer have this issue after updating to the most recent version.
Please let us know if the issue persists, otherwise I would ask you to close this issue.

**Comment by Surbhi2111** [comment]
@LegionaryCohort i already informed u on slack ... 
am not getting it any more ... will close it
