### ISSUE TITLE
[Visualisation Adjustments] Generalise the "Full Vis" Button

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#181]
It would be great to have a collection of checkboxes or similar to control the visualisation:

- Restrict to src/corr/trg domain (only show elements in these domains and directly connected elements)
- Restrict to context (this is what is currently possible)
- Restrict to created elements (and directly connected context elements of course)
- ???

A particularly cool feature here would be to allow combinations that make sense, i.e., restrict to src *and* restrict to context...

**Comment by LegionaryCohort** [comment]
This feature has now been implemented.
All changes have been merged into the stable branch.
