### ISSUE TITLE
[Visualisation Adjustments] Generalise the show/hide/corr labels 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#184]
The current options for handling correspondence labels are really cool.  Why not generalise this to cover all text in the visualisation (including all other edge labels, types, and names of objects)?  

A clean solution would be to route all requests for "labels" to the same util that first processes the raw name and produces the result that fits to whatever is currently set as preferences in the UI.

**Comment by 09Ankita** [comment]
And what should be the default option?

**Comment by anthonyanjorin** [comment]
Let’s go with abbreviated as Usability suggests...

**Comment by LegionaryCohort** [comment]
This feature has now been implemented.
All changes have been merged into the stable branch.
