### ISSUE TITLE
[Apply] I hate the apply button!  I vote for using a double-click on matches to apply them

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#186]
I would prefer using a double-click on a match to apply it.  Using appropriate tool tips, this can be communicated easily to the user.

**Comment by LegionaryCohort** [comment]
Personally I like the Apply button, I hate using double-click (for anything, my PC and Laptop are both set up to minimize double-clicking wherever possible).

Considering that this appears to be a preference issue, perhaps it makes sense to keep the apply button and offer double-clicking as an alternative to do the same thing.

**Comment by anthonyanjorin** [comment]
Ahahaha!  I typically hate buttons in any format :)

Yes -- let's make it an alternative and not a replacement (for old-school users who aren't yet ready to give up menus and buttons and embrace gestures).

**Comment by LegionaryCohort** [comment]
I've added the option for double-clicking to apply matches and merged the changes into the stable branch.
