### ISSUE TITLE
NewTGGRuleWizard not working

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-ui#2]
The wizard for adding a rule to a TGG currently does not work. After entering a name and the name of the schema, clicking on "Finish" results in the message "Please choose a folder so I know where to put the rule!". Then it returns to the wizard page.

**Comment by anthonyanjorin** [comment]
Please update and try again -- I can't reproduce this after fixing #1

**Comment by FStolte** [comment]
I found the problem. When I tried creating a new rule, I was in the Resource perspective, not in the Modeling perspective. Therefore, my explorer was the project explorer and not the model explorer. As a result, the wizard was not able to find my selection since it directly references the model explorer.

I removed that direct reference. Finding the selection should be more robust now.
