### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eMoflon/emoflon-ibex-ui#203]
Hello eMoflon team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the eMoflon project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by Arikae** [comment]
Dear Tamás,

here is the requested snippet. 
Sorry for the late reply.

<tr>
	<td><a href="https://emoflon.org/"></a>eMoflon</td>
	<td>eMoflon is a tool suite for Model-Driven Engineering (MDE) that provides a range of visual and formal languages for (meta)modelling and model management. </td>
	<td>GPL 3.0 and EPL 2.0</td>
	<td>model transformation framework</td>
	<td>Anthony Anjorin, Sebastian Ehmes, Lars Fritsche, Nils Weidmann</td>
</tr>

Thank you for the opportunity!
Lars

**Comment by miklossy** [comment]
Thank you Lars for providing the necessary information!

**Comment by miklossy** [comment]
The `eMoflon` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
