### ISSUE TITLE
Visualization of pattern network not working anymore

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-ui#4]
Hi Tony,

After pulling the current state of all repositories, my visualization of the patterns.xmi file does not work anymore. Instead of showing the pattern network, I get a picture similar to the visualization of the instance files (src.xmi etc.). Visualization of TGG rules is still working as expected.
Since you recently reworked the visualization feature, I think that you may have forgotten to commit something.

Thanks,
Florian

**Comment by anthonyanjorin** [comment]
Hi Florian,

everything seems to be pushed as required.  I simplified the code for the visualisation a bit (perhaps this is the problem):  Now you have to select the ``Pattern`` to get the visualisation, no longer a ``Pattern Body``.   Please check if this works.

Cheers,
Tony

**Comment by FStolte** [comment]
My problem was that I did not realize there was a new project for democles-specific parts of the visualization. Now it works fine!
