### ISSUE TITLE
Icons of the new GT operations in toolbar missing

### ISSUE THREAD

**Issue by RobinOppermann** [eMoflon/emoflon-ibex-ui#46]
The icons of the new GT operations are not shownin the toolbar. Instead a red box is shown.
Another issue: Sometimes all eMoflon Icons are displayed very small (only about quarter of the size of a normal icon)

![grafik](https://user-images.githubusercontent.com/35925661/36423216-48b1f936-163f-11e8-8d2e-9568f87c418a.png)

**Comment by RobinOppermann** [comment]
![grafik](https://user-images.githubusercontent.com/35925661/36423514-86806a30-1640-11e8-8647-5186a2193bd2.png)

**Comment by patrickrobrecht** [comment]
This should be fixed in the latest release.
