### ISSUE TITLE
Strange name for the API

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#65]
for a simple example the name of the generated API is ```DeupbmbsetaxcalculationexamplebusinessrulespatternmatchingAPI``` :(

This is quite a mouthful...    As the generated code is placed in a package with the correct name, why not just take the last Segment + API as name?

**Comment by patrickrobrecht** [comment]
This should be fixed after https://github.com/eMoflon/emoflon-ibex/pull/312 is merged.
