### ISSUE TITLE
Add all dependencies required for using Democles as GT engine

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#67]
I just spent quite some time figuring out which dependencies were necessary and adding them manually.  Please add automatically all dependencies required to use Democles as a GT engine out-of-the-box.

**Comment by patrickrobrecht** [comment]
After https://github.com/eMoflon/emoflon-ibex-democles/pull/58 is merged, only one dependency `org.emoflon.ibex.gt.democles` will be required. The plugin `org.emoflon.ibex.gt.democles` reexports all other required dependencies, such that they will be resolved automatically.

To add `org.emoflon.ibex.gt.democles` to a project's dependencies the build shall be extended (another class implementing the builder extension for Democles) - then everything in the repos emoflon-ibex-ui and emoflon-ibex keeps independent of Democles.
