### ISSUE TITLE
API helper as "Starthilfe" for users

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#69]
I suggest establishing a basis class using the template method pattern.  End users should be able to subclass this basis class and just implement a minimal set of abstract methods in their class to get things running.

A suggestion for such a generic class is attached.  This can be provided by the framework and does not need to be generated all the time.

[GTApp.java.txt](https://github.com/eMoflon/emoflon-ibex-ui/files/1838463/GTApp.java.txt)

**Comment by anthonyanjorin** [comment]
@patrickrobrecht Have you taken a look at the attached class?

**Comment by patrickrobrecht** [comment]
https://github.com/eMoflon/emoflon-ibex/pull/312 implements a pattern matcher independent app. Something like registerUserMetamodels must not be abstract as it can be implemented in the generated code - we require generated code for the meta-model, so we know the packages to import as well.

To deal with Democles we could generate a `...DemoclesApp` extends `...App` (the ... in the name is the same prefix as for the API) which can import `DemoclesGTEngine` and provide a init method with `new DemoclesGTEngine`.

**Comment by anthonyanjorin** [comment]
Sounds good!
