### ISSUE TITLE
Optimise code completion for import statement

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#76]
The import statement is not very friendly right now.

1.  When you type import and hit ctrl+space you only get "Name" as a completion
2.  If you type import "" and then ask for code completion between the "" it works, but when you make your choice there's an annoying " left over at the ending of the statement.

**Comment by patrickrobrecht** [comment]
![import-auto-complete](https://user-images.githubusercontent.com/12370952/38633709-02a7da30-3db0-11e8-999b-b967a1dbfb27.png)

I get correct auto completion proposals when typing `import` and press Ctrl+Space.

**Comment by anthonyanjorin** [comment]
Hmm..   very strange.  I’ll ping you as soon as you can use the handbook to reproduce the exact situation.

**Comment by patrickrobrecht** [comment]
Do you have any EMF projects in your workspace which are not imported already? The editor will search for EMF projects and suggest their `ecore` files.
