### ISSUE TITLE
the java package generated by default violates java naming conventions

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#77]

**Comment by patrickrobrecht** [comment]
The package created upon project creation has the same name as the project. So it may violate Java naming conventions if the project name is uppercase or contains `-` (and maybe some other cases I haven't thought of now).

I'm not sure whether we can deal with all cases. The easiest option would be to put the default content in the default package (so don't generate a package at all).

**Comment by anthonyanjorin** [comment]
Ahh right - ok that’s fine then.  Then I’ll correct the project name!
