### ISSUE TITLE
Missing dependency for newly created GT project:  org.emoflon.ibex.gt.democles

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#78]

**Comment by patrickrobrecht** [comment]
https://github.com/eMoflon/emoflon-ibex/pull/320 offers a new extension point which allows engines to register additional dependencies. In addition an app class for every registered engine will be generated.

https://github.com/eMoflon/emoflon-ibex-democles/pull/61 implements the extension for Democles which will add the required dependency and generate a `..DemoclesApp`.
