### ISSUE TITLE
GT editor: Formatting

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#81]
The formatter enforces this:
	-bottom ->
but I would prefer
        -bottom->

**Comment by patrickrobrecht** [comment]
I decided for `-ref -> target` instead of `-ref->target`  for consistency with other keywords with all are surrounded by exactly one space (all words, but also the `==`, `!=`, `:=` etc. in attribute constraints).

**Comment by anthonyanjorin** [comment]
What is the keyword here?  Shouldn't it then be - ref -> target?  I could live with that I guess.  The point here is that it is supposed to resemble a "link", hence -foo->.  I just feel that -ref looks strange on its own.

**Comment by patrickrobrecht** [comment]
`->` is the keyword here. The `-` and `.` before references and attributes (necessary to provide Xtext code-completion out of the box) are the only exceptions from the convention that all keywords are surrounded by one space - and I think that's fine.
