### ISSUE TITLE
GT Validation Rule:  No 'when' for abstract rules/patterns

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#89]
As when conditions cannot be inherited, it makes no sense to have when clauses for abstract patterns/rules.  This should be flagged as an error (I kept making this mistake constantly).

**Comment by patrickrobrecht** [comment]
You are right that `when`  conditions don't make any sense in abstract rules, but abstract patterns can be used in conditions (after `enforce` or `forbid` if they have ony one clause in DNF). The `abstract` keyword is a possibility to say "don't generate an API class for this pattern, it's just for use in conditions (or refinements)".

**Comment by anthonyanjorin** [comment]
Ok, then let’s give a warning/error only if an abstract pattern/rule has a when clause and is NOT used in a condition.  

In this case it’s certainly meaningless to have the when clause.

Agreed?

**Comment by patrickrobrecht** [comment]
That's something we can do.
